[package]
name = "Prokopakop"
version = "0.1.0"
edition = "2024"

[dependencies]
serde = { version = "1.0.219", features = ["derive"] }
log = "0.4.27"
strum = "0.27.2"
strum_macros = "0.27.2"
env_logger = "0.11.8"
